name: mc_utils
description: Video Player,TextField Custom,Custom Images,Custom Buttons ,Custom Icons, Custom Text, Custom DropDownButton,Custom List, Custom DateTime Format.
version: 0.0.4
homepage: https://github.com/metacodey/mc_utils.git
auther: Metacodeye

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  animated_custom_dropdown: ^3.1.1
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  intl: ^0.19.0
  cached_video_player_plus: ^3.0.2
  file_picker: ^8.0.5
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hexcolor: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.mc_utils
        pluginClass: McUtilsPlugin
      ios:
        pluginClass: McUtilsPlugin


  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/speaker_off.png
    - assets/images/speaker.png


  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
